services:
    - docker
language: python
python:
    - "3.6"
install:
    - docker build -t bdkech/reveal-md .
script:
    # Create the docs directory. This is where we will be publishing from
    # (see the "deploy" section below).
    # Use reveal-md to generate static docs.
    - mkdir -p docs/
    - docker run -v $PWD:/slides -it -p 8080:1948 bdkech/reveal-md reveal-md slides/slides.md --static slides/docs --disable-auto-open --theme white
    # Use reveal-md to generate PDF.
    - docker run -v $PWD:/slides -it -p 8080:1948 bdkech/reveal-md reveal-md slides/slides.md --puppeteer-launch-args="dumpio:true --no-sandbox --disable-setuid-sandbox" --disable-auto-open --theme white --print slides/slides.pdf
    - cp slides.pdf docs/.
# This is an example to deploy to a branch through Travis.
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    # We read the master branch
    on:
        branch: master
    # Take the docs/ directory
    local-dir: docs
    # Publish to the gh-pages branch
    target-branch: gh-pages
    verbose: true
